name: web_ffi
version: 0.7.3
description: Translates dart:ffi calls on the web to WebAssembly using dart:js
repository: https://github.com/darkstarx/web_ffi

publish_to: https://pub.rightbrain.pro

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  js: ^0.6.3
  meta: ^1.3.0
